### ISSUE TITLE
Sentence fragment in `jj init.md`

### ISSUE THREAD

**Issue by joekrall** [chriskrycho/v5.chriskrycho.com#279]
At the second-to-last paragraph of ["Revisions and Revsets"](https://v5.chriskrycho.com/essays/jj-init/#revisions-and-revsets), there's a sentence fragment opening:

![image](https://github.com/chriskrycho/v5.chriskrycho.com/assets/63315344/c5d7718b-e716-4c9f-9c30-74d7e12d7816)

**Comment by chriskrycho** [comment]
Ah, thank you! I’ll push a fix here shortly.
