### ISSUE TITLE
Eleventy type definitions improvements for `addLayoutAlias`

### ISSUE THREAD

**Issue by d2s** [chriskrycho/v5.chriskrycho.com#62]
Copied your `eleventy.d.ts` type definitions of Eleventy to a personal website that I'm slowly converting towards TypeScript. Noticed that there was a missing type signature for `addLayoutAlias` on the `Config` part of the file.

Eleventy's official documentation has more details about the layout aliasing feature.
https://www.11ty.io/docs/layouts/#layout-aliasing

### Code example

This still lack proper testing, but it got me a bit more forward today while I was doing the JavaScript to TypeScript conversion. Thought to share, as it could help to get a bit wider type coverage for the system.

```js
   /**
    * **TODO:** `addLayoutAlias` is still unfinished, not fully tested!
    * @param name string
    * @param filename string
    */
   addLayoutAlias(name: string, filename: string): string | void
```

### Potential changelog items

- Improve `eleventy.d.ts` type definitions
  - Add initial type signature to `addLayoutAlias`

**Comment by chriskrycho** [comment]
Awesome, thank you! I’m going to get dtslint coverage on this whole set and upstream them to DefiniteyTyped in a couple weeks (when I have some time off).

**Comment by chriskrycho** [comment]
Also, I have to say: the lack of a single source for Eleventy’s API makes it suuuuper hard to get full coverage. So I *particularly* appreciate this.

**Comment by d2s** [comment]
Yeah, I had various frustrating moments (documented partly on the [Twitter thread](https://twitter.com/autiomaa/status/1202306400011063297)) while doing the move to TypeScript-based structure. Haven't yet rewritten much (compared how much you have in your repository), but generally feeling a bit frustrated by the lack of clearly understandable documentation on how to do the TypeScript type definition files.

One potential improvement to your type files would be to add the JSDoc comments about what each feature is, even while the type `@params` details itself would be omitted, as TypeScript itself does fine for those. Could use something similar to this, where each of the type definitions also points to the Eleventy documentation, allowing people to hover the TypeScript code to get quick pointers to the documentation:

```js
  /**
   * Layout aliasing
   * 
   * - https://www.11ty.dev/docs/layouts/#layout-aliasing
   * - https://github.com/11ty/eleventy/search?q=addLayoutAlias&unscoped_q=addLayoutAlias
   */
   addLayoutAlias(from: string, to: string): string | void
```

Changed the parameter names to match the original implementation, even while `from` & `to` might not be as clear about what should be in those parameters (when thinking about structure of the content).

Another potential option could be to have link to the GitHub code search for finding all of the mentions of the code for easier access to the original implementation. For example:
- https://github.com/11ty/eleventy/search?q=addLayoutAlias&unscoped_q=addLayoutAlias

VS Code (at least) will display those JSDoc comments by rendering the Markdown syntax inside of the description text, making it possible to include more clarified documentation structure about details, if needed.

```js
  /**
   * - [GitHub search: addLayoutAlias](https://github.com/11ty/eleventy/search?q=addLayoutAlias&unscoped_q=addLayoutAlias)
   */
```

**Comment by chriskrycho** [comment]
Actually, one of the reasons I've put the docs (and not just links, though *adding* links to the source is a great idea!) is because then when you trigger autocomplete, you can see all of that description right then and there:

![docs](https://user-images.githubusercontent.com/2403023/70376159-249a4200-18c3-11ea-98fd-05191f04a687.png "screenshot of docs shown on autocomplete")

Additionally, it's *very* helpful for the JSDoc comments to include information about their intent. Types do not *replace* docs; they *complement* each other. The `@param` declarations *don't* need to include types—that a few of mine still do is a holdover from when I briefly attempted to do this using TS' JSDoc support instead of just going full TypeScript—but their being documented is a big win for usability:

![more-docs](https://user-images.githubusercontent.com/2403023/70376199-a38f7a80-18c3-11ea-8f50-5d09de9d3020.png "screenshot of docs with param comments shown on hover")

**Comment by d2s** [comment]
Oh, that looks really useful. Didn't notice yet, as was just trying to convert the existing parts to work. 👍 

Thank you for the hard work. 😄

**Comment by chriskrycho** [comment]
No problem! I have, uhh, a [lot] of experience in this space. 😆 

[lot]: https://ember-cli-typescript.com

**Comment by d2s** [comment]
Latest Eleventy `v0.10.0-beta.1` version has a bit better JSDoc annotations.
- [eleventy/src/Eleventy.js](https://github.com/11ty/eleventy/blob/master/src/Eleventy.js) was improved.

Those might help figuring out more of the type definitions in the future.

- [Release 🚧🚧 Eleventy 🕚⚡️ v0.10.0 Beta 1 🚧🚧 · 11ty/eleventy](https://github.com/11ty/eleventy/releases/tag/v0.10.0-beta.1)

(Still a lot of JSDoc annotations missing, but a good direction overall.)

**Comment by chriskrycho** [comment]
Thank you for noting that! 🎉

**Comment by chriskrycho** [comment]
Realistically, I’m unlikely to touch this in the future. Please do feel free to keep iterating on those types (including publishing them).
